server:
  port: 18088

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    locator:
      discovery:
        enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false

feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
thread:
  pool:
    coreSize: 50
    maxSize: 100
    keepAlive: 60
    blockingSize: 500
