#端口号
server:
  port: 18089

#nacos地址
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #sentinel地址
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: tx-gmall-group
  #redis
  redis:
    host: 192.168.146.128
  #zipkin
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  #sleuth(取样概率，1表示全部取用)
  sleuth:
    sampler:
      probability: 1

#feign
feign:
  sentinel:
    enabled: true #是否启动feign

#日志输出
logging:
  level:
    com.auguigu.gmall: debug
