#端口号
server:
  port: 18081

#nacos地址
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #sentinel地址
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: tx-gmall-group
  #数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.146.128:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  #redis
  redis:
    host: 192.168.146.128
  #zipkin
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  #sleuth(取样概率，1表示全部取用)
  sleuth:
    sampler:
      probability: 1

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml  #读取映射文件
  global-config:
    db-config:
      id-type: auto #使用数据库默认的自增
  type-aliases-package: com.atguigu.gmall.pms.entity

#feign
feign:
  sentinel:
    enabled: true #是否启动feign

#日志输出
logging:
  level:
    com.auguigu.gmall: debug
